#!/bin/sh
if [ $# -gt 0 ] ; then
   python make_show/mk.py $1 > config/shows/rehearse.xml
fi
python code/burrito.py config/shows/rehearse.xml config/pinning_table.xml config/rehearse.xml config/triggers.xml
