#!/bin/sh
if [ $# -gt 0 ] ; then
   python code/burrito.py $1 config/pinning_table.xml config/trial.xml config/triggers.xml
   exit 0
fi
python code/burrito.py config/shows/show.xml config/pinning_table.xml config/trial.xml config/triggers.xml

