#!/bin/sh
if [ $# -gt 0 ] ; then
   python make_show/mktest.py $1 > config/burrito.xml 
   python code/xml_client.py config/burrito.xml config/rehearse.xml config/triggers.xml 
   exit 0
fi
python make_show/mktest.py > config/burrito.xml 
python code/xml_client.py config/burrito.xml config/rehearse.xml config/triggers.xml 

